# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BlockmanGo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'R.swift'
pod 'RxSwift',    '~> 4.0.0-rc.0'
pod 'RxCocoa',    '~> 4.0.0-rc.0'
pod 'SnapKit', '~> 4.0.0'
pod 'Kingfisher', '~> 4.6.0'
pod 'Moya', '~> 11.0'
pod 'HandyJSON', '~> 4.1.1'
pod 'FCUUID'
  # Pods for BlockmanGo

end
