# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BlockmanGo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
pod 'R.swift'
pod 'SnapKit', '~> 4.0.0'
pod 'Kingfisher', '~> 4.6.0'
pod 'Moya', '~> 11.0'
pod 'HandyJSON', '~> 4.1.1'
pod 'FCUUID'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'IQKeyboardManagerSwift'
pod 'FBSDKLoginKit'
pod 'GoogleSignIn'
  # Pods for BlockmanGo

end

target 'BlockmanGo_Dev' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'R.swift'
    pod 'SnapKit', '~> 4.0.0'
    pod 'Kingfisher', '~> 4.6.0'
    pod 'Moya', '~> 11.0'
    pod 'HandyJSON', '~> 4.1.1'
    pod 'FCUUID'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'IQKeyboardManagerSwift'
    pod 'FBSDKLoginKit'
    pod 'GoogleSignIn'
    # Pods for BlockmanGo
    
end
