//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.clr` struct is generated, and contains static references to 1 color palettes.
  /// NOTE: R.clr is deprecated and will be removed in a future R.swift version.
  struct clr {
    /// This `R.clr.appColor` struct is generated, and contains static references to 80 colors.
    struct appColor {
      /// <span style='background-color: #000000; color: #FFFFFF; padding: 1px 3px;'>#000000</span> black
      static let black = Rswift.ColorPaletteItemResource(name: "black", red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #0000FF; color: #FFFF00; padding: 1px 3px;'>#0000FF</span> blue
      static let blue = Rswift.ColorPaletteItemResource(name: "blue", red: 0.0, green: 0.0, blue: 1.0, alpha: 1.0)
      /// <span style='background-color: #007C4D; color: #FF83B2; padding: 1px 3px;'>#007C4D</span> _007c4d
      static let _007c4d = Rswift.ColorPaletteItemResource(name: "_007c4d", red: 0.0, green: 0.4862745098, blue: 0.3019607843, alpha: 1.0)
      /// <span style='background-color: #007E5C; color: #FF81A3; padding: 1px 3px;'>#007E5C</span> _007e5c
      static let _007e5c = Rswift.ColorPaletteItemResource(name: "_007e5c", red: 0.0, green: 0.4941176471, blue: 0.3607843137, alpha: 1.0)
      /// <span style='background-color: #007F42; color: #FF80BD; padding: 1px 3px;'>#007F42</span> _007f42
      static let _007f42 = Rswift.ColorPaletteItemResource(name: "_007f42", red: 0.0, green: 0.4980392157, blue: 0.2588235294, alpha: 1.0)
      /// <span style='background-color: #00925A; color: #FF6DA5; padding: 1px 3px;'>#00925A</span> _00925a
      static let _00925a = Rswift.ColorPaletteItemResource(name: "_00925a", red: 0.0, green: 0.5725490196, blue: 0.3529411765, alpha: 1.0)
      /// <span style='background-color: #0193B7; color: #FE6C48; padding: 1px 3px;'>#0193B7</span> _0193b7
      static let _0193b7 = Rswift.ColorPaletteItemResource(name: "_0193b7", red: 0.003921568627, green: 0.5764705882, blue: 0.7176470588, alpha: 1.0)
      /// <span style='background-color: #0AB950; color: #F546AF; padding: 1px 3px;'>#0AB950</span> _0ab950
      static let _0ab950 = Rswift.ColorPaletteItemResource(name: "_0ab950", red: 0.03921568627, green: 0.7254901961, blue: 0.3137254902, alpha: 1.0)
      /// <span style='background-color: #0AB97D; color: #F54682; padding: 1px 3px;'>#0AB97D</span> _0AB97D
      static let _0AB97D = Rswift.ColorPaletteItemResource(name: "_0AB97D", red: 0.03921568627, green: 0.7254901961, blue: 0.4901960784, alpha: 1.0)
      /// <span style='background-color: #0D634C; color: #F29CB3; padding: 1px 3px;'>#0D634C</span> _0d634c
      static let _0d634c = Rswift.ColorPaletteItemResource(name: "_0d634c", red: 0.05098039216, green: 0.3882352941, blue: 0.2980392157, alpha: 1.0)
      /// <span style='background-color: #0D634C; color: #F29CB3; padding: 1px 3px;'>#0D634C</span> mainBackground
      static let mainBackground = Rswift.ColorPaletteItemResource(name: "mainBackground", red: 0.05098039216, green: 0.3882352941, blue: 0.2980392157, alpha: 1.0)
      /// <span style='background-color: #10F025; color: #EF0FDA; padding: 1px 3px;'>#10F025</span> _10f025
      static let _10f025 = Rswift.ColorPaletteItemResource(name: "_10f025", red: 0.06274509804, green: 0.9411764706, blue: 0.1450980392, alpha: 1.0)
      /// <span style='background-color: #19CC71; color: #E6338E; padding: 1px 3px;'>#19CC71</span> _19cc71
      static let _19cc71 = Rswift.ColorPaletteItemResource(name: "_19cc71", red: 0.09803921569, green: 0.8, blue: 0.4431372549, alpha: 1.0)
      /// <span style='background-color: #1D8C49; color: #E273B6; padding: 1px 3px;'>#1D8C49</span> _1d8c49
      static let _1d8c49 = Rswift.ColorPaletteItemResource(name: "_1d8c49", red: 0.1137254902, green: 0.5490196078, blue: 0.2862745098, alpha: 1.0)
      /// <span style='background-color: #20BAD1; color: #DF452E; padding: 1px 3px;'>#20BAD1</span> text_light
      static let text_light = Rswift.ColorPaletteItemResource(name: "text_light", red: 0.1254901961, green: 0.7294117647, blue: 0.8196078431, alpha: 1.0)
      /// <span style='background-color: #23A965; color: #DC569A; padding: 1px 3px;'>#23A965</span> _23a965
      static let _23a965 = Rswift.ColorPaletteItemResource(name: "_23a965", red: 0.137254902, green: 0.662745098, blue: 0.3960784314, alpha: 1.0)
      /// <span style='background-color: #26AA62; color: #D9559D; padding: 1px 3px;'>#26AA62</span> _26aa62
      static let _26aa62 = Rswift.ColorPaletteItemResource(name: "_26aa62", red: 0.1490196078, green: 0.6666666667, blue: 0.3843137255, alpha: 1.0)
      /// <span style='background-color: #28A95B; color: #D756A4; padding: 1px 3px;'>#28A95B</span> _22a556
      static let _22a556 = Rswift.ColorPaletteItemResource(name: "_22a556", red: 0.1568627451, green: 0.662745098, blue: 0.3568627451, alpha: 1.0)
      /// <span style='background-color: #28A95B; color: #D756A4; padding: 1px 3px;'>#28A95B</span> _28a95b
      static let _28a95b = Rswift.ColorPaletteItemResource(name: "_28a95b", red: 0.1568627451, green: 0.662745098, blue: 0.3568627451, alpha: 1.0)
      /// <span style='background-color: #2F1C00; color: #D0E3FF; padding: 1px 3px;'>#2F1C00</span> _2f1c00
      static let _2f1c00 = Rswift.ColorPaletteItemResource(name: "_2f1c00", red: 0.1843137255, green: 0.1098039216, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #327C68; color: #CD8397; padding: 1px 3px;'>#327C68</span> separator
      static let separator = Rswift.ColorPaletteItemResource(name: "separator", red: 0.1960784314, green: 0.4862745098, blue: 0.4078431373, alpha: 1.0)
      /// <span style='background-color: #333333; color: #CCCCCC; padding: 1px 3px;'>#333333</span> _333333
      static let _333333 = Rswift.ColorPaletteItemResource(name: "_333333", red: 0.2, green: 0.2, blue: 0.2, alpha: 1.0)
      /// <span style='background-color: #341E00; color: #CBE1FF; padding: 1px 3px;'>#341E00</span> _341e00
      static let _341e00 = Rswift.ColorPaletteItemResource(name: "_341e00", red: 0.2039215686, green: 0.1176470588, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #555555; color: #AAAAAA; padding: 1px 3px;'>#555555</span> _555555
      static let _555555 = Rswift.ColorPaletteItemResource(name: "_555555", red: 0.333333333333333, green: 0.333333333333333, blue: 0.333333333333333, alpha: 1.0)
      /// <span style='background-color: #5E3F00; color: #A1C0FF; padding: 1px 3px;'>#5E3F00</span> _5e3f00
      static let _5e3f00 = Rswift.ColorPaletteItemResource(name: "_5e3f00", red: 0.368627451, green: 0.2470588235, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #644D22; color: #9BB2DD; padding: 1px 3px;'>#644D22</span> _644d22
      static let _644d22 = Rswift.ColorPaletteItemResource(name: "_644d22", red: 0.3921568627, green: 0.3019607843, blue: 0.1333333333, alpha: 1.0)
      /// <span style='background-color: #653E00; color: #9AC1FF; padding: 1px 3px;'>#653E00</span> _653e00
      static let _653e00 = Rswift.ColorPaletteItemResource(name: "_653e00", red: 0.3960784314, green: 0.2431372549, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #666666; color: #999999; padding: 1px 3px;'>#666666</span> _666666
      static let _666666 = Rswift.ColorPaletteItemResource(name: "_666666", red: 0.4, green: 0.4, blue: 0.4, alpha: 1.0)
      /// <span style='background-color: #70C07A; color: #8F3F85; padding: 1px 3px;'>#70C07A</span> _70c07a
      static let _70c07a = Rswift.ColorPaletteItemResource(name: "_70c07a", red: 0.4392156863, green: 0.7529411765, blue: 0.4784313725, alpha: 1.0)
      /// <span style='background-color: #799684; color: #86697B; padding: 1px 3px;'>#799684</span> _799684
      static let _799684 = Rswift.ColorPaletteItemResource(name: "_799684", red: 0.4745098039, green: 0.5882352941, blue: 0.5176470588, alpha: 1.0)
      /// <span style='background-color: #7A4E38; color: #85B1C7; padding: 1px 3px;'>#7A4E38</span> _7a4e38
      static let _7a4e38 = Rswift.ColorPaletteItemResource(name: "_7a4e38", red: 0.4784313725, green: 0.3058823529, blue: 0.2196078431, alpha: 1.0)
      /// <span style='background-color: #7FB9A9; color: #804656; padding: 1px 3px;'>#7FB9A9</span> text_normal
      static let text_normal = Rswift.ColorPaletteItemResource(name: "text_normal", red: 0.4980392157, green: 0.7254901961, blue: 0.662745098, alpha: 1.0)
      /// <span style='background-color: #844501; color: #7BBAFE; padding: 1px 3px;'>#844501</span> _844501
      static let _844501 = Rswift.ColorPaletteItemResource(name: "_844501", red: 0.5176470588, green: 0.2705882353, blue: 0.003921568627, alpha: 1.0)
      /// <span style='background-color: #8F4D00; color: #70B2FF; padding: 1px 3px;'>#8F4D00</span> _8f4d00
      static let _8f4d00 = Rswift.ColorPaletteItemResource(name: "_8f4d00", red: 0.5607843137, green: 0.3019607843, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #91660B; color: #6E99F4; padding: 1px 3px;'>#91660B</span> _91660b
      static let _91660b = Rswift.ColorPaletteItemResource(name: "_91660b", red: 0.568627451, green: 0.4, blue: 0.0431372549, alpha: 1.0)
      /// <span style='background-color: #9A5C00; color: #65A3FF; padding: 1px 3px;'>#9A5C00</span> _9a5c00
      static let _9a5c00 = Rswift.ColorPaletteItemResource(name: "_9a5c00", red: 0.6039215686, green: 0.3607843137, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #A7A7A7; color: #585858; padding: 1px 3px;'>#A7A7A7</span> _a7a7a7
      static let _a7a7a7 = Rswift.ColorPaletteItemResource(name: "_a7a7a7", red: 0.6549019608, green: 0.6549019608, blue: 0.6549019608, alpha: 1.0)
      /// <span style='background-color: #AAAAAA; color: #555555; padding: 1px 3px;'>#AAAAAA</span> _aaaaaa
      static let _aaaaaa = Rswift.ColorPaletteItemResource(name: "_aaaaaa", red: 0.666666666666667, green: 0.666666666666667, blue: 0.666666666666667, alpha: 1.0)
      /// <span style='background-color: #B17F63; color: #4E809C; padding: 1px 3px;'>#B17F63</span> _b17f63
      static let _b17f63 = Rswift.ColorPaletteItemResource(name: "_b17f63", red: 0.6941176471, green: 0.4980392157, blue: 0.3882352941, alpha: 1.0)
      /// <span style='background-color: #B39558; color: #4C6AA7; padding: 1px 3px;'>#B39558</span> _b39558
      static let _b39558 = Rswift.ColorPaletteItemResource(name: "_b39558", red: 0.7019607843, green: 0.5843137255, blue: 0.3450980392, alpha: 1.0)
      /// <span style='background-color: #BBFFDC; color: #440023; padding: 1px 3px;'>#BBFFDC</span> _bbffdc
      static let _bbffdc = Rswift.ColorPaletteItemResource(name: "_bbffdc", red: 0.7333333333, green: 1.0, blue: 0.862745098, alpha: 1.0)
      /// <span style='background-color: #C38039; color: #3C7FC6; padding: 1px 3px;'>#C38039</span> _a36b2e
      static let _a36b2e = Rswift.ColorPaletteItemResource(name: "_a36b2e", red: 0.7647058824, green: 0.5019607843, blue: 0.2235294118, alpha: 1.0)
      /// <span style='background-color: #C38039; color: #3C7FC6; padding: 1px 3px;'>#C38039</span> _c38039
      static let _c38039 = Rswift.ColorPaletteItemResource(name: "_c38039", red: 0.7647058824, green: 0.5019607843, blue: 0.2235294118, alpha: 1.0)
      /// <span style='background-color: #C8A16B; color: #375E94; padding: 1px 3px;'>#C8A16B</span> _c8a16b
      static let _c8a16b = Rswift.ColorPaletteItemResource(name: "_c8a16b", red: 0.7843137255, green: 0.631372549, blue: 0.4196078431, alpha: 1.0)
      /// <span style='background-color: #CBAD83; color: #34527C; padding: 1px 3px;'>#CBAD83</span> _cbad83
      static let _cbad83 = Rswift.ColorPaletteItemResource(name: "_cbad83", red: 0.7960784314, green: 0.6784313725, blue: 0.5137254902, alpha: 1.0)
      /// <span style='background-color: #CCE1D9; color: #331E26; padding: 1px 3px;'>#CCE1D9</span> _cce1d9
      static let _cce1d9 = Rswift.ColorPaletteItemResource(name: "_cce1d9", red: 0.8, green: 0.8823529412, blue: 0.8509803922, alpha: 1.0)
      /// <span style='background-color: #D1A566; color: #2E5A99; padding: 1px 3px;'>#D1A566</span> _d1a566
      static let _d1a566 = Rswift.ColorPaletteItemResource(name: "_d1a566", red: 0.8196078431, green: 0.6470588235, blue: 0.4, alpha: 1.0)
      /// <span style='background-color: #D43636; color: #2BC9C9; padding: 1px 3px;'>#D43636</span> _d43636
      static let _d43636 = Rswift.ColorPaletteItemResource(name: "_d43636", red: 0.831372549, green: 0.2117647059, blue: 0.2117647059, alpha: 1.0)
      /// <span style='background-color: #D52626; color: #2AD9D9; padding: 1px 3px;'>#D52626</span> _d52626
      static let _d52626 = Rswift.ColorPaletteItemResource(name: "_d52626", red: 0.8352941176, green: 0.1490196078, blue: 0.1490196078, alpha: 1.0)
      /// <span style='background-color: #D62121; color: #29DEDE; padding: 1px 3px;'>#D62121</span> _d62121
      static let _d62121 = Rswift.ColorPaletteItemResource(name: "_d62121", red: 0.8392156863, green: 0.1294117647, blue: 0.1294117647, alpha: 1.0)
      /// <span style='background-color: #D74242; color: #28BDBD; padding: 1px 3px;'>#D74242</span> _d74242
      static let _d74242 = Rswift.ColorPaletteItemResource(name: "_d74242", red: 0.8431372549, green: 0.2588235294, blue: 0.2588235294, alpha: 1.0)
      /// <span style='background-color: #E4CAA5; color: #1B355A; padding: 1px 3px;'>#E4CAA5</span> _e4caa5
      static let _e4caa5 = Rswift.ColorPaletteItemResource(name: "_e4caa5", red: 0.8941176471, green: 0.7921568627, blue: 0.6470588235, alpha: 1.0)
      /// <span style='background-color: #E55642; color: #1AA9BD; padding: 1px 3px;'>#E55642</span> _e55642
      static let _e55642 = Rswift.ColorPaletteItemResource(name: "_e55642", red: 0.8980392157, green: 0.337254902, blue: 0.2588235294, alpha: 1.0)
      /// <span style='background-color: #E60012; color: #19FFED; padding: 1px 3px;'>#E60012</span> _e60012
      static let _e60012 = Rswift.ColorPaletteItemResource(name: "_e60012", red: 0.9019607843, green: 0.0, blue: 0.07058823529, alpha: 1.0)
      /// <span style='background-color: #E7C99E; color: #183661; padding: 1px 3px;'>#E7C99E</span> _e7c99e
      static let _e7c99e = Rswift.ColorPaletteItemResource(name: "_e7c99e", red: 0.9058823529, green: 0.7882352941, blue: 0.6196078431, alpha: 1.0)
      /// <span style='background-color: #EAD5B6; color: #152A49; padding: 1px 3px;'>#EAD5B6</span> _ead5b6
      static let _ead5b6 = Rswift.ColorPaletteItemResource(name: "_ead5b6", red: 0.9176470588, green: 0.8352941176, blue: 0.7137254902, alpha: 1.0)
      /// <span style='background-color: #EB8A00; color: #1475FF; padding: 1px 3px;'>#EB8A00</span> _eb8a00
      static let _eb8a00 = Rswift.ColorPaletteItemResource(name: "_eb8a00", red: 0.9215686275, green: 0.5411764706, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #EED5A0; color: #112A5F; padding: 1px 3px;'>#EED5A0</span> _eed5a0
      static let _eed5a0 = Rswift.ColorPaletteItemResource(name: "_eed5a0", red: 0.9333333333, green: 0.8352941176, blue: 0.6274509804, alpha: 1.0)
      /// <span style='background-color: #EF2B1C; color: #10D4E3; padding: 1px 3px;'>#EF2B1C</span> _ef2b1c
      static let _ef2b1c = Rswift.ColorPaletteItemResource(name: "_ef2b1c", red: 0.937254902, green: 0.168627451, blue: 0.1098039216, alpha: 1.0)
      /// <span style='background-color: #EFD8B8; color: #102747; padding: 1px 3px;'>#EFD8B8</span> _efd8b8
      static let _efd8b8 = Rswift.ColorPaletteItemResource(name: "_efd8b8", red: 0.937254902, green: 0.8470588235, blue: 0.7215686275, alpha: 1.0)
      /// <span style='background-color: #F0D5AE; color: #0F2A51; padding: 1px 3px;'>#F0D5AE</span> _f0d5ae
      static let _f0d5ae = Rswift.ColorPaletteItemResource(name: "_f0d5ae", red: 0.9411764706, green: 0.8352941176, blue: 0.6823529412, alpha: 1.0)
      /// <span style='background-color: #F1795F; color: #0E86A0; padding: 1px 3px;'>#F1795F</span> _f1795f
      static let _f1795f = Rswift.ColorPaletteItemResource(name: "_f1795f", red: 0.9450980392, green: 0.4745098039, blue: 0.3725490196, alpha: 1.0)
      /// <span style='background-color: #F1DAB6; color: #0E2549; padding: 1px 3px;'>#F1DAB6</span> _f1dab6
      static let _f1dab6 = Rswift.ColorPaletteItemResource(name: "_f1dab6", red: 0.9450980392, green: 0.8549019608, blue: 0.7137254902, alpha: 1.0)
      /// <span style='background-color: #F5DDBB; color: #0A2244; padding: 1px 3px;'>#F5DDBB</span> _ f5ddbb
      static let _F5ddbb = Rswift.ColorPaletteItemResource(name: "_ f5ddbb", red: 0.9607843137, green: 0.8666666667, blue: 0.7333333333, alpha: 1.0)
      /// <span style='background-color: #F6EDD2; color: #09122D; padding: 1px 3px;'>#F6EDD2</span> _f6edd2
      static let _f6edd2 = Rswift.ColorPaletteItemResource(name: "_f6edd2", red: 0.9647058824, green: 0.9294117647, blue: 0.8235294118, alpha: 1.0)
      /// <span style='background-color: #FAE7CA; color: #051835; padding: 1px 3px;'>#FAE7CA</span> _fae7ca
      static let _fae7ca = Rswift.ColorPaletteItemResource(name: "_fae7ca", red: 0.9803921569, green: 0.9058823529, blue: 0.7921568627, alpha: 1.0)
      /// <span style='background-color: #FAEBD3; color: #05142C; padding: 1px 3px;'>#FAEBD3</span> _faebd3
      static let _faebd3 = Rswift.ColorPaletteItemResource(name: "_faebd3", red: 0.9803921569, green: 0.9215686275, blue: 0.8274509804, alpha: 1.0)
      /// <span style='background-color: #FCF1DE; color: #030E21; padding: 1px 3px;'>#FCF1DE</span> _fcf1de
      static let _fcf1de = Rswift.ColorPaletteItemResource(name: "_fcf1de", red: 0.9882352941, green: 0.9450980392, blue: 0.8705882353, alpha: 1.0)
      /// <span style='background-color: #FEF1DE; color: #010E21; padding: 1px 3px;'>#FEF1DE</span> _fef1de
      static let _fef1de = Rswift.ColorPaletteItemResource(name: "_fef1de", red: 0.9960784314, green: 0.9450980392, blue: 0.8705882353, alpha: 1.0)
      /// <span style='background-color: #FEFEFE; color: #010101; padding: 1px 3px;'>#FEFEFE</span> _FEFEFE
      static let _FEFEFE = Rswift.ColorPaletteItemResource(name: "_FEFEFE", red: 0.9960784314, green: 0.9960784314, blue: 0.9960784314, alpha: 1.0)
      /// <span style='background-color: #FF0000; color: #00FFFF; padding: 1px 3px;'>#FF0000</span> red
      static let red = Rswift.ColorPaletteItemResource(name: "red", red: 1.0, green: 0.0, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #FFA800; color: #0057FF; padding: 1px 3px;'>#FFA800</span> _fa800
      static let _fa800 = Rswift.ColorPaletteItemResource(name: "_fa800", red: 1.0, green: 0.6588235294, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #FFF1DB; color: #000E24; padding: 1px 3px;'>#FFF1DB</span> _fff1db
      static let _fff1db = Rswift.ColorPaletteItemResource(name: "_fff1db", red: 1.0, green: 0.9450980392, blue: 0.8588235294, alpha: 1.0)
      /// <span style='background-color: #FFF2DE; color: #000D21; padding: 1px 3px;'>#FFF2DE</span> _fff2de
      static let _fff2de = Rswift.ColorPaletteItemResource(name: "_fff2de", red: 1.0, green: 0.9490196078, blue: 0.8705882353, alpha: 1.0)
      /// <span style='background-color: #FFF8E9; color: #000716; padding: 1px 3px;'>#FFF8E9</span> _fff8e9
      static let _fff8e9 = Rswift.ColorPaletteItemResource(name: "_fff8e9", red: 1.0, green: 0.9725490196, blue: 0.9137254902, alpha: 1.0)
      /// <span style='background-color: #FFF9F0; color: #00060F; padding: 1px 3px;'>#FFF9F0</span> _fff9f0
      static let _fff9f0 = Rswift.ColorPaletteItemResource(name: "_fff9f0", red: 1.0, green: 0.9764705882, blue: 0.9411764706, alpha: 1.0)
      /// <span style='background-color: #FFFAF2; color: #00050D; padding: 1px 3px;'>#FFFAF2</span> _fffaf2
      static let _fffaf2 = Rswift.ColorPaletteItemResource(name: "_fffaf2", red: 1.0, green: 0.9803921569, blue: 0.9490196078, alpha: 1.0)
      /// <span style='background-color: #FFFEFE; color: #000101; padding: 1px 3px;'>#FFFEFE</span> _fffefe
      static let _fffefe = Rswift.ColorPaletteItemResource(name: "_fffefe", red: 1.0, green: 0.9960784314, blue: 0.9960784314, alpha: 1.0)
      /// <span style='background-color: #FFFF00; color: #0000FF; padding: 1px 3px;'>#FFFF00</span> yellow
      static let yellow = Rswift.ColorPaletteItemResource(name: "yellow", red: 1.0, green: 1.0, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #FFFFFF; color: #000000; padding: 1px 3px;'>#FFFFFF</span> white
      static let white = Rswift.ColorPaletteItemResource(name: "white", red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
      
      /// <span style='background-color: #000000; color: #FFFFFF; padding: 1px 3px;'>#000000</span> black
      /// 
      /// UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)
      static func black(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #0000FF; color: #FFFF00; padding: 1px 3px;'>#0000FF</span> blue
      /// 
      /// UIColor(red: 0.0, green: 0.0, blue: 1.0, alpha: 1.0)
      static func blue(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.0, green: 0.0, blue: 1.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #007C4D; color: #FF83B2; padding: 1px 3px;'>#007C4D</span> _007c4d
      /// 
      /// UIColor(red: 0.0, green: 0.4862745098, blue: 0.3019607843, alpha: 1.0)
      static func _007c4d(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.0, green: 0.4862745098, blue: 0.3019607843, alpha: 1.0)
      }
      
      /// <span style='background-color: #007E5C; color: #FF81A3; padding: 1px 3px;'>#007E5C</span> _007e5c
      /// 
      /// UIColor(red: 0.0, green: 0.4941176471, blue: 0.3607843137, alpha: 1.0)
      static func _007e5c(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.0, green: 0.4941176471, blue: 0.3607843137, alpha: 1.0)
      }
      
      /// <span style='background-color: #007F42; color: #FF80BD; padding: 1px 3px;'>#007F42</span> _007f42
      /// 
      /// UIColor(red: 0.0, green: 0.4980392157, blue: 0.2588235294, alpha: 1.0)
      static func _007f42(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.0, green: 0.4980392157, blue: 0.2588235294, alpha: 1.0)
      }
      
      /// <span style='background-color: #00925A; color: #FF6DA5; padding: 1px 3px;'>#00925A</span> _00925a
      /// 
      /// UIColor(red: 0.0, green: 0.5725490196, blue: 0.3529411765, alpha: 1.0)
      static func _00925a(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.0, green: 0.5725490196, blue: 0.3529411765, alpha: 1.0)
      }
      
      /// <span style='background-color: #0193B7; color: #FE6C48; padding: 1px 3px;'>#0193B7</span> _0193b7
      /// 
      /// UIColor(red: 0.003921568627, green: 0.5764705882, blue: 0.7176470588, alpha: 1.0)
      static func _0193b7(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.003921568627, green: 0.5764705882, blue: 0.7176470588, alpha: 1.0)
      }
      
      /// <span style='background-color: #0AB950; color: #F546AF; padding: 1px 3px;'>#0AB950</span> _0ab950
      /// 
      /// UIColor(red: 0.03921568627, green: 0.7254901961, blue: 0.3137254902, alpha: 1.0)
      static func _0ab950(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.03921568627, green: 0.7254901961, blue: 0.3137254902, alpha: 1.0)
      }
      
      /// <span style='background-color: #0AB97D; color: #F54682; padding: 1px 3px;'>#0AB97D</span> _0AB97D
      /// 
      /// UIColor(red: 0.03921568627, green: 0.7254901961, blue: 0.4901960784, alpha: 1.0)
      static func _0AB97D(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.03921568627, green: 0.7254901961, blue: 0.4901960784, alpha: 1.0)
      }
      
      /// <span style='background-color: #0D634C; color: #F29CB3; padding: 1px 3px;'>#0D634C</span> _0d634c
      /// 
      /// UIColor(red: 0.05098039216, green: 0.3882352941, blue: 0.2980392157, alpha: 1.0)
      static func _0d634c(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.05098039216, green: 0.3882352941, blue: 0.2980392157, alpha: 1.0)
      }
      
      /// <span style='background-color: #0D634C; color: #F29CB3; padding: 1px 3px;'>#0D634C</span> mainBackground
      /// 
      /// UIColor(red: 0.05098039216, green: 0.3882352941, blue: 0.2980392157, alpha: 1.0)
      static func mainBackground(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.05098039216, green: 0.3882352941, blue: 0.2980392157, alpha: 1.0)
      }
      
      /// <span style='background-color: #10F025; color: #EF0FDA; padding: 1px 3px;'>#10F025</span> _10f025
      /// 
      /// UIColor(red: 0.06274509804, green: 0.9411764706, blue: 0.1450980392, alpha: 1.0)
      static func _10f025(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.06274509804, green: 0.9411764706, blue: 0.1450980392, alpha: 1.0)
      }
      
      /// <span style='background-color: #19CC71; color: #E6338E; padding: 1px 3px;'>#19CC71</span> _19cc71
      /// 
      /// UIColor(red: 0.09803921569, green: 0.8, blue: 0.4431372549, alpha: 1.0)
      static func _19cc71(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.09803921569, green: 0.8, blue: 0.4431372549, alpha: 1.0)
      }
      
      /// <span style='background-color: #1D8C49; color: #E273B6; padding: 1px 3px;'>#1D8C49</span> _1d8c49
      /// 
      /// UIColor(red: 0.1137254902, green: 0.5490196078, blue: 0.2862745098, alpha: 1.0)
      static func _1d8c49(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.1137254902, green: 0.5490196078, blue: 0.2862745098, alpha: 1.0)
      }
      
      /// <span style='background-color: #20BAD1; color: #DF452E; padding: 1px 3px;'>#20BAD1</span> text_light
      /// 
      /// UIColor(red: 0.1254901961, green: 0.7294117647, blue: 0.8196078431, alpha: 1.0)
      static func text_light(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.1254901961, green: 0.7294117647, blue: 0.8196078431, alpha: 1.0)
      }
      
      /// <span style='background-color: #23A965; color: #DC569A; padding: 1px 3px;'>#23A965</span> _23a965
      /// 
      /// UIColor(red: 0.137254902, green: 0.662745098, blue: 0.3960784314, alpha: 1.0)
      static func _23a965(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.137254902, green: 0.662745098, blue: 0.3960784314, alpha: 1.0)
      }
      
      /// <span style='background-color: #26AA62; color: #D9559D; padding: 1px 3px;'>#26AA62</span> _26aa62
      /// 
      /// UIColor(red: 0.1490196078, green: 0.6666666667, blue: 0.3843137255, alpha: 1.0)
      static func _26aa62(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.1490196078, green: 0.6666666667, blue: 0.3843137255, alpha: 1.0)
      }
      
      /// <span style='background-color: #28A95B; color: #D756A4; padding: 1px 3px;'>#28A95B</span> _22a556
      /// 
      /// UIColor(red: 0.1568627451, green: 0.662745098, blue: 0.3568627451, alpha: 1.0)
      static func _22a556(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.1568627451, green: 0.662745098, blue: 0.3568627451, alpha: 1.0)
      }
      
      /// <span style='background-color: #28A95B; color: #D756A4; padding: 1px 3px;'>#28A95B</span> _28a95b
      /// 
      /// UIColor(red: 0.1568627451, green: 0.662745098, blue: 0.3568627451, alpha: 1.0)
      static func _28a95b(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.1568627451, green: 0.662745098, blue: 0.3568627451, alpha: 1.0)
      }
      
      /// <span style='background-color: #2F1C00; color: #D0E3FF; padding: 1px 3px;'>#2F1C00</span> _2f1c00
      /// 
      /// UIColor(red: 0.1843137255, green: 0.1098039216, blue: 0.0, alpha: 1.0)
      static func _2f1c00(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.1843137255, green: 0.1098039216, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #327C68; color: #CD8397; padding: 1px 3px;'>#327C68</span> separator
      /// 
      /// UIColor(red: 0.1960784314, green: 0.4862745098, blue: 0.4078431373, alpha: 1.0)
      static func separator(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.1960784314, green: 0.4862745098, blue: 0.4078431373, alpha: 1.0)
      }
      
      /// <span style='background-color: #333333; color: #CCCCCC; padding: 1px 3px;'>#333333</span> _333333
      /// 
      /// UIColor(red: 0.2, green: 0.2, blue: 0.2, alpha: 1.0)
      static func _333333(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.2, green: 0.2, blue: 0.2, alpha: 1.0)
      }
      
      /// <span style='background-color: #341E00; color: #CBE1FF; padding: 1px 3px;'>#341E00</span> _341e00
      /// 
      /// UIColor(red: 0.2039215686, green: 0.1176470588, blue: 0.0, alpha: 1.0)
      static func _341e00(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.2039215686, green: 0.1176470588, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #555555; color: #AAAAAA; padding: 1px 3px;'>#555555</span> _555555
      /// 
      /// UIColor(red: 0.333333333333333, green: 0.333333333333333, blue: 0.333333333333333, alpha: 1.0)
      static func _555555(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.333333333333333, green: 0.333333333333333, blue: 0.333333333333333, alpha: 1.0)
      }
      
      /// <span style='background-color: #5E3F00; color: #A1C0FF; padding: 1px 3px;'>#5E3F00</span> _5e3f00
      /// 
      /// UIColor(red: 0.368627451, green: 0.2470588235, blue: 0.0, alpha: 1.0)
      static func _5e3f00(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.368627451, green: 0.2470588235, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #644D22; color: #9BB2DD; padding: 1px 3px;'>#644D22</span> _644d22
      /// 
      /// UIColor(red: 0.3921568627, green: 0.3019607843, blue: 0.1333333333, alpha: 1.0)
      static func _644d22(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.3921568627, green: 0.3019607843, blue: 0.1333333333, alpha: 1.0)
      }
      
      /// <span style='background-color: #653E00; color: #9AC1FF; padding: 1px 3px;'>#653E00</span> _653e00
      /// 
      /// UIColor(red: 0.3960784314, green: 0.2431372549, blue: 0.0, alpha: 1.0)
      static func _653e00(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.3960784314, green: 0.2431372549, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #666666; color: #999999; padding: 1px 3px;'>#666666</span> _666666
      /// 
      /// UIColor(red: 0.4, green: 0.4, blue: 0.4, alpha: 1.0)
      static func _666666(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.4, green: 0.4, blue: 0.4, alpha: 1.0)
      }
      
      /// <span style='background-color: #70C07A; color: #8F3F85; padding: 1px 3px;'>#70C07A</span> _70c07a
      /// 
      /// UIColor(red: 0.4392156863, green: 0.7529411765, blue: 0.4784313725, alpha: 1.0)
      static func _70c07a(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.4392156863, green: 0.7529411765, blue: 0.4784313725, alpha: 1.0)
      }
      
      /// <span style='background-color: #799684; color: #86697B; padding: 1px 3px;'>#799684</span> _799684
      /// 
      /// UIColor(red: 0.4745098039, green: 0.5882352941, blue: 0.5176470588, alpha: 1.0)
      static func _799684(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.4745098039, green: 0.5882352941, blue: 0.5176470588, alpha: 1.0)
      }
      
      /// <span style='background-color: #7A4E38; color: #85B1C7; padding: 1px 3px;'>#7A4E38</span> _7a4e38
      /// 
      /// UIColor(red: 0.4784313725, green: 0.3058823529, blue: 0.2196078431, alpha: 1.0)
      static func _7a4e38(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.4784313725, green: 0.3058823529, blue: 0.2196078431, alpha: 1.0)
      }
      
      /// <span style='background-color: #7FB9A9; color: #804656; padding: 1px 3px;'>#7FB9A9</span> text_normal
      /// 
      /// UIColor(red: 0.4980392157, green: 0.7254901961, blue: 0.662745098, alpha: 1.0)
      static func text_normal(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.4980392157, green: 0.7254901961, blue: 0.662745098, alpha: 1.0)
      }
      
      /// <span style='background-color: #844501; color: #7BBAFE; padding: 1px 3px;'>#844501</span> _844501
      /// 
      /// UIColor(red: 0.5176470588, green: 0.2705882353, blue: 0.003921568627, alpha: 1.0)
      static func _844501(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.5176470588, green: 0.2705882353, blue: 0.003921568627, alpha: 1.0)
      }
      
      /// <span style='background-color: #8F4D00; color: #70B2FF; padding: 1px 3px;'>#8F4D00</span> _8f4d00
      /// 
      /// UIColor(red: 0.5607843137, green: 0.3019607843, blue: 0.0, alpha: 1.0)
      static func _8f4d00(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.5607843137, green: 0.3019607843, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #91660B; color: #6E99F4; padding: 1px 3px;'>#91660B</span> _91660b
      /// 
      /// UIColor(red: 0.568627451, green: 0.4, blue: 0.0431372549, alpha: 1.0)
      static func _91660b(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.568627451, green: 0.4, blue: 0.0431372549, alpha: 1.0)
      }
      
      /// <span style='background-color: #9A5C00; color: #65A3FF; padding: 1px 3px;'>#9A5C00</span> _9a5c00
      /// 
      /// UIColor(red: 0.6039215686, green: 0.3607843137, blue: 0.0, alpha: 1.0)
      static func _9a5c00(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.6039215686, green: 0.3607843137, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #A7A7A7; color: #585858; padding: 1px 3px;'>#A7A7A7</span> _a7a7a7
      /// 
      /// UIColor(red: 0.6549019608, green: 0.6549019608, blue: 0.6549019608, alpha: 1.0)
      static func _a7a7a7(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.6549019608, green: 0.6549019608, blue: 0.6549019608, alpha: 1.0)
      }
      
      /// <span style='background-color: #AAAAAA; color: #555555; padding: 1px 3px;'>#AAAAAA</span> _aaaaaa
      /// 
      /// UIColor(red: 0.666666666666667, green: 0.666666666666667, blue: 0.666666666666667, alpha: 1.0)
      static func _aaaaaa(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.666666666666667, green: 0.666666666666667, blue: 0.666666666666667, alpha: 1.0)
      }
      
      /// <span style='background-color: #B17F63; color: #4E809C; padding: 1px 3px;'>#B17F63</span> _b17f63
      /// 
      /// UIColor(red: 0.6941176471, green: 0.4980392157, blue: 0.3882352941, alpha: 1.0)
      static func _b17f63(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.6941176471, green: 0.4980392157, blue: 0.3882352941, alpha: 1.0)
      }
      
      /// <span style='background-color: #B39558; color: #4C6AA7; padding: 1px 3px;'>#B39558</span> _b39558
      /// 
      /// UIColor(red: 0.7019607843, green: 0.5843137255, blue: 0.3450980392, alpha: 1.0)
      static func _b39558(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.7019607843, green: 0.5843137255, blue: 0.3450980392, alpha: 1.0)
      }
      
      /// <span style='background-color: #BBFFDC; color: #440023; padding: 1px 3px;'>#BBFFDC</span> _bbffdc
      /// 
      /// UIColor(red: 0.7333333333, green: 1.0, blue: 0.862745098, alpha: 1.0)
      static func _bbffdc(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.7333333333, green: 1.0, blue: 0.862745098, alpha: 1.0)
      }
      
      /// <span style='background-color: #C38039; color: #3C7FC6; padding: 1px 3px;'>#C38039</span> _a36b2e
      /// 
      /// UIColor(red: 0.7647058824, green: 0.5019607843, blue: 0.2235294118, alpha: 1.0)
      static func _a36b2e(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.7647058824, green: 0.5019607843, blue: 0.2235294118, alpha: 1.0)
      }
      
      /// <span style='background-color: #C38039; color: #3C7FC6; padding: 1px 3px;'>#C38039</span> _c38039
      /// 
      /// UIColor(red: 0.7647058824, green: 0.5019607843, blue: 0.2235294118, alpha: 1.0)
      static func _c38039(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.7647058824, green: 0.5019607843, blue: 0.2235294118, alpha: 1.0)
      }
      
      /// <span style='background-color: #C8A16B; color: #375E94; padding: 1px 3px;'>#C8A16B</span> _c8a16b
      /// 
      /// UIColor(red: 0.7843137255, green: 0.631372549, blue: 0.4196078431, alpha: 1.0)
      static func _c8a16b(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.7843137255, green: 0.631372549, blue: 0.4196078431, alpha: 1.0)
      }
      
      /// <span style='background-color: #CBAD83; color: #34527C; padding: 1px 3px;'>#CBAD83</span> _cbad83
      /// 
      /// UIColor(red: 0.7960784314, green: 0.6784313725, blue: 0.5137254902, alpha: 1.0)
      static func _cbad83(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.7960784314, green: 0.6784313725, blue: 0.5137254902, alpha: 1.0)
      }
      
      /// <span style='background-color: #CCE1D9; color: #331E26; padding: 1px 3px;'>#CCE1D9</span> _cce1d9
      /// 
      /// UIColor(red: 0.8, green: 0.8823529412, blue: 0.8509803922, alpha: 1.0)
      static func _cce1d9(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.8, green: 0.8823529412, blue: 0.8509803922, alpha: 1.0)
      }
      
      /// <span style='background-color: #D1A566; color: #2E5A99; padding: 1px 3px;'>#D1A566</span> _d1a566
      /// 
      /// UIColor(red: 0.8196078431, green: 0.6470588235, blue: 0.4, alpha: 1.0)
      static func _d1a566(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.8196078431, green: 0.6470588235, blue: 0.4, alpha: 1.0)
      }
      
      /// <span style='background-color: #D43636; color: #2BC9C9; padding: 1px 3px;'>#D43636</span> _d43636
      /// 
      /// UIColor(red: 0.831372549, green: 0.2117647059, blue: 0.2117647059, alpha: 1.0)
      static func _d43636(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.831372549, green: 0.2117647059, blue: 0.2117647059, alpha: 1.0)
      }
      
      /// <span style='background-color: #D52626; color: #2AD9D9; padding: 1px 3px;'>#D52626</span> _d52626
      /// 
      /// UIColor(red: 0.8352941176, green: 0.1490196078, blue: 0.1490196078, alpha: 1.0)
      static func _d52626(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.8352941176, green: 0.1490196078, blue: 0.1490196078, alpha: 1.0)
      }
      
      /// <span style='background-color: #D62121; color: #29DEDE; padding: 1px 3px;'>#D62121</span> _d62121
      /// 
      /// UIColor(red: 0.8392156863, green: 0.1294117647, blue: 0.1294117647, alpha: 1.0)
      static func _d62121(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.8392156863, green: 0.1294117647, blue: 0.1294117647, alpha: 1.0)
      }
      
      /// <span style='background-color: #D74242; color: #28BDBD; padding: 1px 3px;'>#D74242</span> _d74242
      /// 
      /// UIColor(red: 0.8431372549, green: 0.2588235294, blue: 0.2588235294, alpha: 1.0)
      static func _d74242(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.8431372549, green: 0.2588235294, blue: 0.2588235294, alpha: 1.0)
      }
      
      /// <span style='background-color: #E4CAA5; color: #1B355A; padding: 1px 3px;'>#E4CAA5</span> _e4caa5
      /// 
      /// UIColor(red: 0.8941176471, green: 0.7921568627, blue: 0.6470588235, alpha: 1.0)
      static func _e4caa5(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.8941176471, green: 0.7921568627, blue: 0.6470588235, alpha: 1.0)
      }
      
      /// <span style='background-color: #E55642; color: #1AA9BD; padding: 1px 3px;'>#E55642</span> _e55642
      /// 
      /// UIColor(red: 0.8980392157, green: 0.337254902, blue: 0.2588235294, alpha: 1.0)
      static func _e55642(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.8980392157, green: 0.337254902, blue: 0.2588235294, alpha: 1.0)
      }
      
      /// <span style='background-color: #E60012; color: #19FFED; padding: 1px 3px;'>#E60012</span> _e60012
      /// 
      /// UIColor(red: 0.9019607843, green: 0.0, blue: 0.07058823529, alpha: 1.0)
      static func _e60012(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9019607843, green: 0.0, blue: 0.07058823529, alpha: 1.0)
      }
      
      /// <span style='background-color: #E7C99E; color: #183661; padding: 1px 3px;'>#E7C99E</span> _e7c99e
      /// 
      /// UIColor(red: 0.9058823529, green: 0.7882352941, blue: 0.6196078431, alpha: 1.0)
      static func _e7c99e(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9058823529, green: 0.7882352941, blue: 0.6196078431, alpha: 1.0)
      }
      
      /// <span style='background-color: #EAD5B6; color: #152A49; padding: 1px 3px;'>#EAD5B6</span> _ead5b6
      /// 
      /// UIColor(red: 0.9176470588, green: 0.8352941176, blue: 0.7137254902, alpha: 1.0)
      static func _ead5b6(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9176470588, green: 0.8352941176, blue: 0.7137254902, alpha: 1.0)
      }
      
      /// <span style='background-color: #EB8A00; color: #1475FF; padding: 1px 3px;'>#EB8A00</span> _eb8a00
      /// 
      /// UIColor(red: 0.9215686275, green: 0.5411764706, blue: 0.0, alpha: 1.0)
      static func _eb8a00(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9215686275, green: 0.5411764706, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #EED5A0; color: #112A5F; padding: 1px 3px;'>#EED5A0</span> _eed5a0
      /// 
      /// UIColor(red: 0.9333333333, green: 0.8352941176, blue: 0.6274509804, alpha: 1.0)
      static func _eed5a0(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9333333333, green: 0.8352941176, blue: 0.6274509804, alpha: 1.0)
      }
      
      /// <span style='background-color: #EF2B1C; color: #10D4E3; padding: 1px 3px;'>#EF2B1C</span> _ef2b1c
      /// 
      /// UIColor(red: 0.937254902, green: 0.168627451, blue: 0.1098039216, alpha: 1.0)
      static func _ef2b1c(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.937254902, green: 0.168627451, blue: 0.1098039216, alpha: 1.0)
      }
      
      /// <span style='background-color: #EFD8B8; color: #102747; padding: 1px 3px;'>#EFD8B8</span> _efd8b8
      /// 
      /// UIColor(red: 0.937254902, green: 0.8470588235, blue: 0.7215686275, alpha: 1.0)
      static func _efd8b8(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.937254902, green: 0.8470588235, blue: 0.7215686275, alpha: 1.0)
      }
      
      /// <span style='background-color: #F0D5AE; color: #0F2A51; padding: 1px 3px;'>#F0D5AE</span> _f0d5ae
      /// 
      /// UIColor(red: 0.9411764706, green: 0.8352941176, blue: 0.6823529412, alpha: 1.0)
      static func _f0d5ae(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9411764706, green: 0.8352941176, blue: 0.6823529412, alpha: 1.0)
      }
      
      /// <span style='background-color: #F1795F; color: #0E86A0; padding: 1px 3px;'>#F1795F</span> _f1795f
      /// 
      /// UIColor(red: 0.9450980392, green: 0.4745098039, blue: 0.3725490196, alpha: 1.0)
      static func _f1795f(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9450980392, green: 0.4745098039, blue: 0.3725490196, alpha: 1.0)
      }
      
      /// <span style='background-color: #F1DAB6; color: #0E2549; padding: 1px 3px;'>#F1DAB6</span> _f1dab6
      /// 
      /// UIColor(red: 0.9450980392, green: 0.8549019608, blue: 0.7137254902, alpha: 1.0)
      static func _f1dab6(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9450980392, green: 0.8549019608, blue: 0.7137254902, alpha: 1.0)
      }
      
      /// <span style='background-color: #F5DDBB; color: #0A2244; padding: 1px 3px;'>#F5DDBB</span> _ f5ddbb
      /// 
      /// UIColor(red: 0.9607843137, green: 0.8666666667, blue: 0.7333333333, alpha: 1.0)
      static func _F5ddbb(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9607843137, green: 0.8666666667, blue: 0.7333333333, alpha: 1.0)
      }
      
      /// <span style='background-color: #F6EDD2; color: #09122D; padding: 1px 3px;'>#F6EDD2</span> _f6edd2
      /// 
      /// UIColor(red: 0.9647058824, green: 0.9294117647, blue: 0.8235294118, alpha: 1.0)
      static func _f6edd2(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9647058824, green: 0.9294117647, blue: 0.8235294118, alpha: 1.0)
      }
      
      /// <span style='background-color: #FAE7CA; color: #051835; padding: 1px 3px;'>#FAE7CA</span> _fae7ca
      /// 
      /// UIColor(red: 0.9803921569, green: 0.9058823529, blue: 0.7921568627, alpha: 1.0)
      static func _fae7ca(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9803921569, green: 0.9058823529, blue: 0.7921568627, alpha: 1.0)
      }
      
      /// <span style='background-color: #FAEBD3; color: #05142C; padding: 1px 3px;'>#FAEBD3</span> _faebd3
      /// 
      /// UIColor(red: 0.9803921569, green: 0.9215686275, blue: 0.8274509804, alpha: 1.0)
      static func _faebd3(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9803921569, green: 0.9215686275, blue: 0.8274509804, alpha: 1.0)
      }
      
      /// <span style='background-color: #FCF1DE; color: #030E21; padding: 1px 3px;'>#FCF1DE</span> _fcf1de
      /// 
      /// UIColor(red: 0.9882352941, green: 0.9450980392, blue: 0.8705882353, alpha: 1.0)
      static func _fcf1de(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9882352941, green: 0.9450980392, blue: 0.8705882353, alpha: 1.0)
      }
      
      /// <span style='background-color: #FEF1DE; color: #010E21; padding: 1px 3px;'>#FEF1DE</span> _fef1de
      /// 
      /// UIColor(red: 0.9960784314, green: 0.9450980392, blue: 0.8705882353, alpha: 1.0)
      static func _fef1de(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9960784314, green: 0.9450980392, blue: 0.8705882353, alpha: 1.0)
      }
      
      /// <span style='background-color: #FEFEFE; color: #010101; padding: 1px 3px;'>#FEFEFE</span> _FEFEFE
      /// 
      /// UIColor(red: 0.9960784314, green: 0.9960784314, blue: 0.9960784314, alpha: 1.0)
      static func _FEFEFE(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9960784314, green: 0.9960784314, blue: 0.9960784314, alpha: 1.0)
      }
      
      /// <span style='background-color: #FF0000; color: #00FFFF; padding: 1px 3px;'>#FF0000</span> red
      /// 
      /// UIColor(red: 1.0, green: 0.0, blue: 0.0, alpha: 1.0)
      static func red(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 1.0, green: 0.0, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #FFA800; color: #0057FF; padding: 1px 3px;'>#FFA800</span> _fa800
      /// 
      /// UIColor(red: 1.0, green: 0.6588235294, blue: 0.0, alpha: 1.0)
      static func _fa800(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 1.0, green: 0.6588235294, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #FFF1DB; color: #000E24; padding: 1px 3px;'>#FFF1DB</span> _fff1db
      /// 
      /// UIColor(red: 1.0, green: 0.9450980392, blue: 0.8588235294, alpha: 1.0)
      static func _fff1db(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 1.0, green: 0.9450980392, blue: 0.8588235294, alpha: 1.0)
      }
      
      /// <span style='background-color: #FFF2DE; color: #000D21; padding: 1px 3px;'>#FFF2DE</span> _fff2de
      /// 
      /// UIColor(red: 1.0, green: 0.9490196078, blue: 0.8705882353, alpha: 1.0)
      static func _fff2de(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 1.0, green: 0.9490196078, blue: 0.8705882353, alpha: 1.0)
      }
      
      /// <span style='background-color: #FFF8E9; color: #000716; padding: 1px 3px;'>#FFF8E9</span> _fff8e9
      /// 
      /// UIColor(red: 1.0, green: 0.9725490196, blue: 0.9137254902, alpha: 1.0)
      static func _fff8e9(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 1.0, green: 0.9725490196, blue: 0.9137254902, alpha: 1.0)
      }
      
      /// <span style='background-color: #FFF9F0; color: #00060F; padding: 1px 3px;'>#FFF9F0</span> _fff9f0
      /// 
      /// UIColor(red: 1.0, green: 0.9764705882, blue: 0.9411764706, alpha: 1.0)
      static func _fff9f0(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 1.0, green: 0.9764705882, blue: 0.9411764706, alpha: 1.0)
      }
      
      /// <span style='background-color: #FFFAF2; color: #00050D; padding: 1px 3px;'>#FFFAF2</span> _fffaf2
      /// 
      /// UIColor(red: 1.0, green: 0.9803921569, blue: 0.9490196078, alpha: 1.0)
      static func _fffaf2(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 1.0, green: 0.9803921569, blue: 0.9490196078, alpha: 1.0)
      }
      
      /// <span style='background-color: #FFFEFE; color: #000101; padding: 1px 3px;'>#FFFEFE</span> _fffefe
      /// 
      /// UIColor(red: 1.0, green: 0.9960784314, blue: 0.9960784314, alpha: 1.0)
      static func _fffefe(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 1.0, green: 0.9960784314, blue: 0.9960784314, alpha: 1.0)
      }
      
      /// <span style='background-color: #FFFF00; color: #0000FF; padding: 1px 3px;'>#FFFF00</span> yellow
      /// 
      /// UIColor(red: 1.0, green: 1.0, blue: 0.0, alpha: 1.0)
      static func yellow(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 1.0, green: 1.0, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #FFFFFF; color: #000000; padding: 1px 3px;'>#FFFFFF</span> white
      /// 
      /// UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
      static func white(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `AppColor.clr`.
    static let appColorClr = Rswift.FileResource(bundle: R.hostingBundle, name: "AppColor", pathExtension: "clr")
    /// Resource file `EngineResource`.
    static let engineResource = Rswift.FileResource(bundle: R.hostingBundle, name: "EngineResource", pathExtension: "")
    
    /// `bundle.url(forResource: "AppColor", withExtension: "clr")`
    static func appColorClr(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.appColorClr
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "EngineResource", withExtension: "")`
    static func engineResource(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.engineResource
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 38 images.
  struct image {
    /// Image `account_info_background`.
    static let account_info_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "account_info_background")
    /// Image `check_update_background`.
    static let check_update_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "check_update_background")
    /// Image `check_update_progress_background`.
    static let check_update_progress_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "check_update_progress_background")
    /// Image `check_update_progress`.
    static let check_update_progress = Rswift.ImageResource(bundle: R.hostingBundle, name: "check_update_progress")
    /// Image `common_default_userimage`.
    static let common_default_userimage = Rswift.ImageResource(bundle: R.hostingBundle, name: "common_default_userimage")
    /// Image `decoration`.
    static let decoration = Rswift.ImageResource(bundle: R.hostingBundle, name: "decoration")
    /// Image `email`.
    static let email = Rswift.ImageResource(bundle: R.hostingBundle, name: "email")
    /// Image `friends`.
    static let friends = Rswift.ImageResource(bundle: R.hostingBundle, name: "friends")
    /// Image `game_backgorund`.
    static let game_backgorund = Rswift.ImageResource(bundle: R.hostingBundle, name: "game_backgorund")
    /// Image `game_item_background`.
    static let game_item_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "game_item_background")
    /// Image `game_like_number`.
    static let game_like_number = Rswift.ImageResource(bundle: R.hostingBundle, name: "game_like_number")
    /// Image `game_like`.
    static let game_like = Rswift.ImageResource(bundle: R.hostingBundle, name: "game_like")
    /// Image `game_liked`.
    static let game_liked = Rswift.ImageResource(bundle: R.hostingBundle, name: "game_liked")
    /// Image `game_mask`.
    static let game_mask = Rswift.ImageResource(bundle: R.hostingBundle, name: "game_mask")
    /// Image `game_mode_background`.
    static let game_mode_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "game_mode_background")
    /// Image `game_play`.
    static let game_play = Rswift.ImageResource(bundle: R.hostingBundle, name: "game_play")
    /// Image `gender_female`.
    static let gender_female = Rswift.ImageResource(bundle: R.hostingBundle, name: "gender_female")
    /// Image `gender_male`.
    static let gender_male = Rswift.ImageResource(bundle: R.hostingBundle, name: "gender_male")
    /// Image `general_alert_background`.
    static let general_alert_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "general_alert_background")
    /// Image `general_back`.
    static let general_back = Rswift.ImageResource(bundle: R.hostingBundle, name: "general_back")
    /// Image `general_button_background_normal`.
    static let general_button_background_normal = Rswift.ImageResource(bundle: R.hostingBundle, name: "general_button_background_normal")
    /// Image `general_button_background_selected`.
    static let general_button_background_selected = Rswift.ImageResource(bundle: R.hostingBundle, name: "general_button_background_selected")
    /// Image `general_close`.
    static let general_close = Rswift.ImageResource(bundle: R.hostingBundle, name: "general_close")
    /// Image `general_recharge`.
    static let general_recharge = Rswift.ImageResource(bundle: R.hostingBundle, name: "general_recharge")
    /// Image `general_red_dot`.
    static let general_red_dot = Rswift.ImageResource(bundle: R.hostingBundle, name: "general_red_dot")
    /// Image `home_bottom_bar`.
    static let home_bottom_bar = Rswift.ImageResource(bundle: R.hostingBundle, name: "home_bottom_bar")
    /// Image `home_play`.
    static let home_play = Rswift.ImageResource(bundle: R.hostingBundle, name: "home_play")
    /// Image `launch_background`.
    static let launch_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "launch_background")
    /// Image `launch_bulletin`.
    static let launch_bulletin = Rswift.ImageResource(bundle: R.hostingBundle, name: "launch_bulletin")
    /// Image `launch_cloud_left`.
    static let launch_cloud_left = Rswift.ImageResource(bundle: R.hostingBundle, name: "launch_cloud_left")
    /// Image `launch_cloud_right`.
    static let launch_cloud_right = Rswift.ImageResource(bundle: R.hostingBundle, name: "launch_cloud_right")
    /// Image `launch_join_background`.
    static let launch_join_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "launch_join_background")
    /// Image `launch_logo`.
    static let launch_logo = Rswift.ImageResource(bundle: R.hostingBundle, name: "launch_logo")
    /// Image `launch_sky`.
    static let launch_sky = Rswift.ImageResource(bundle: R.hostingBundle, name: "launch_sky")
    /// Image `setting`.
    static let setting = Rswift.ImageResource(bundle: R.hostingBundle, name: "setting")
    /// Image `shop`.
    static let shop = Rswift.ImageResource(bundle: R.hostingBundle, name: "shop")
    /// Image `tribe`.
    static let tribe = Rswift.ImageResource(bundle: R.hostingBundle, name: "tribe")
    /// Image `vip_1`.
    static let vip_1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "vip_1")
    
    /// `UIImage(named: "account_info_background", bundle: ..., traitCollection: ...)`
    static func account_info_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.account_info_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "check_update_background", bundle: ..., traitCollection: ...)`
    static func check_update_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.check_update_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "check_update_progress", bundle: ..., traitCollection: ...)`
    static func check_update_progress(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.check_update_progress, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "check_update_progress_background", bundle: ..., traitCollection: ...)`
    static func check_update_progress_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.check_update_progress_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common_default_userimage", bundle: ..., traitCollection: ...)`
    static func common_default_userimage(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.common_default_userimage, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "decoration", bundle: ..., traitCollection: ...)`
    static func decoration(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.decoration, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "email", bundle: ..., traitCollection: ...)`
    static func email(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.email, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "friends", bundle: ..., traitCollection: ...)`
    static func friends(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.friends, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "game_backgorund", bundle: ..., traitCollection: ...)`
    static func game_backgorund(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.game_backgorund, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "game_item_background", bundle: ..., traitCollection: ...)`
    static func game_item_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.game_item_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "game_like", bundle: ..., traitCollection: ...)`
    static func game_like(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.game_like, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "game_like_number", bundle: ..., traitCollection: ...)`
    static func game_like_number(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.game_like_number, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "game_liked", bundle: ..., traitCollection: ...)`
    static func game_liked(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.game_liked, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "game_mask", bundle: ..., traitCollection: ...)`
    static func game_mask(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.game_mask, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "game_mode_background", bundle: ..., traitCollection: ...)`
    static func game_mode_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.game_mode_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "game_play", bundle: ..., traitCollection: ...)`
    static func game_play(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.game_play, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "gender_female", bundle: ..., traitCollection: ...)`
    static func gender_female(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gender_female, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "gender_male", bundle: ..., traitCollection: ...)`
    static func gender_male(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gender_male, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "general_alert_background", bundle: ..., traitCollection: ...)`
    static func general_alert_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.general_alert_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "general_back", bundle: ..., traitCollection: ...)`
    static func general_back(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.general_back, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "general_button_background_normal", bundle: ..., traitCollection: ...)`
    static func general_button_background_normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.general_button_background_normal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "general_button_background_selected", bundle: ..., traitCollection: ...)`
    static func general_button_background_selected(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.general_button_background_selected, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "general_close", bundle: ..., traitCollection: ...)`
    static func general_close(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.general_close, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "general_recharge", bundle: ..., traitCollection: ...)`
    static func general_recharge(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.general_recharge, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "general_red_dot", bundle: ..., traitCollection: ...)`
    static func general_red_dot(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.general_red_dot, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "home_bottom_bar", bundle: ..., traitCollection: ...)`
    static func home_bottom_bar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_bottom_bar, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "home_play", bundle: ..., traitCollection: ...)`
    static func home_play(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_play, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "launch_background", bundle: ..., traitCollection: ...)`
    static func launch_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launch_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "launch_bulletin", bundle: ..., traitCollection: ...)`
    static func launch_bulletin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launch_bulletin, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "launch_cloud_left", bundle: ..., traitCollection: ...)`
    static func launch_cloud_left(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launch_cloud_left, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "launch_cloud_right", bundle: ..., traitCollection: ...)`
    static func launch_cloud_right(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launch_cloud_right, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "launch_join_background", bundle: ..., traitCollection: ...)`
    static func launch_join_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launch_join_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "launch_logo", bundle: ..., traitCollection: ...)`
    static func launch_logo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launch_logo, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "launch_sky", bundle: ..., traitCollection: ...)`
    static func launch_sky(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launch_sky, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "setting", bundle: ..., traitCollection: ...)`
    static func setting(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.setting, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "shop", bundle: ..., traitCollection: ...)`
    static func shop(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.shop, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tribe", bundle: ..., traitCollection: ...)`
    static func tribe(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tribe, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "vip_1", bundle: ..., traitCollection: ...)`
    static func vip_1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.vip_1, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard {
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
